[package]
name = "bobbin"
version = "0.1.0"
authors = ["Nathan West <Lucretiel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
horrorshow = "0.8.3"
http = "0.2.1"
hyper = "0.13.7"
joinery = "2.0.0"
lazy_format= { version = "1.8.3", features = ["horrorshow"] }
paw = "1.0.0"
reqwest = { version = "0.10.1", features = ["json"] }
secrecy = { version = "0.7.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3.15", features = [ "paw" ] }
tokio = { version = "0.2.21", default-feature = false, features = ["rt-threaded", "macros"] }
warp = "0.2.3"
futures = "0.3.5"

[package.metadata.docs.rs]
all-features = true
